### ISSUE TITLE
Mushroom Kingdom - Prime Minister not spawning

### ISSUE THREAD

**Issue by P0nk** [P0nk/Cosmic#204]
"(...) in the Mush Kingdom the Prime Minister isn't spawning, the princess doesn't offer the interaction to spawn him either."

> 14:16:01.870 [nioEventLoopGroup-3-21] ERROR npc.NPCScriptManager - Error performing NPC script action for npc: 1300013
javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "list" is null
	at java.util.Collections.unmodifiableList(Collections.java:1319) ~[?:?]
	at net.server.world.Party.getEligibleMembers(Party.java:160) ~[classes/:?]
	at scripting.event.EventInstanceManager.registerParty(EventInstanceManager.java:364) ~[classes/:?]
	at scripting.event.EventManager.startInstance(EventManager.java:633) ~[classes/:?]
	at scripting.event.EventManager.startInstance(EventManager.java:589) ~[classes/:?]
	at scripting.event.EventManager.startInstance(EventManager.java:585) ~[classes/:?]
	at <js>.action(<eval>:47) ~[?:?]
	at org.graalvm.polyglot.Value.execute(Value.java:880) ~[graal-sdk-22.2.0.jar:?]

**Comment by yuzumika** [comment]
For what it's worth, I was able to complete the entire Mushroom Kingdom questline by playing through it normally (including spawning the Prime Minister).
