### ISSUE TITLE
Error when i try to run sv with IntelliJ idea

### ISSUE THREAD

**Issue by Dalk2ness** [P0nk/Cosmic#43]
i got this error please help
---------------------------------------
java.lang.NoSuchFieldException: modifiers
    at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
    at tools.AutoJCE.removeCryptographyRestrictions(AutoJCE.java:32)
    at net.server.Server.main(Server.java:974)
Failed to remove cryptography restrictions

**Comment by P0nk** [comment]
This should not be an issue with newer Java versions. What version of Java are you running?
